src/Controllers/DinnersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NerdDinner.Models;
using PagedList;

namespace NerdDinner.Controllers
{
    public class DinnersController : Controller
    {
        private NerdDinnerContext db = new NerdDinnerContext();

        //
        // GET: /Dinners/
        private const int PageSize = 25;
        public ActionResult Index(int? page)
        {
            int pageIndex = page ?? 1;

            var dinners = db.Dinners.Where(d => d.EventDate >= DateTime.Now).OrderBy(d => d.EventDate);
            return View(dinners.ToPagedList(pageIndex, PageSize));
        }

        //
        // GET: /Dinners/Details/5

        public ActionResult Details(int id = 0)
        {
            Dinner dinner = db.Dinners.Find(id);
            if (dinner == null)
            {
                return HttpNotFound();
            }
            return View(dinner);
        }

        //
        // GET: /Dinners/Create

        [Authorize]
        public ActionResult Create()
        {
            var dinner = new Dinner()
            {
                EventDate = DateTime.Now.AddDays(7),
                HostedBy = User.Identity.Name
            };

            return View(dinner);
        }

        //
        // POST: /Dinners/Create

        [HttpPost, Authorize, ValidateAntiForgeryToken]
        public ActionResult Create(Dinner dinner)
        {
            if (ModelState.IsValid)
            {
                dinner.HostedBy = User.Identity.Name;

                RSVP rsvp = new RSVP();
                rsvp.AttendeeName = User.Identity.Name;

                dinner.RSVPs = new List<RSVP>();
                dinner.RSVPs.Add(rsvp);

                db.Dinners.Add(dinner);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dinner);
        }

        //
        // GET: /Dinners/Edit/5

        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            Dinner dinner = db.Dinners.Find(id);
            if (dinner == null)
            {
                return HttpNotFound();
            }
            if (!dinner.IsHostedBy(User.Identity.Name))
            {
                return View("InvalidOwner");
            }
            return View(dinner);
        }

        //
        // POST: /Dinners/Edit/5

        [HttpPost, Authorize, ValidateAntiForgeryToken]
        public ActionResult Edit(Dinner dinner)
        {
            if (!dinner.IsHostedBy(User.Identity.Name))
            {
                return View("InvalidOwner");
            }

            if (ModelState.IsValid)
            {
                db.Entry(dinner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dinner);
        }

        //
        // GET: /Dinners/Delete/5

        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Dinner dinner = db.Dinners.Find(id);
            if (dinner == null)
            {
                return HttpNotFound();
            }
            if (!dinner.IsHostedBy(User.Identity.Name))
            {
                return View("InvalidOwner");
            }
            return View(dinner);
        }

        //
        // POST: /Dinners/Delete/5

        [HttpPost, ActionName("Delete"), Authorize, ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dinner dinner = db.Dinners.Find(id);

            if (!dinner.IsHostedBy(User.Identity.Name))
            {
                return View("InvalidOwner");
            }

            db.Dinners.Remove(dinner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult WebSlicePopular()
        {
            ViewData["Title"] = "Popular Nerd Dinners";
            var model = from dinner in db.Dinners
                        where dinner.EventDate >= DateTime.Now
                        orderby dinner.RSVPs.Count descending
                        select dinner;
            return View("WebSlice", model.Take(5));
        }

        public ActionResult WebSliceUpcoming()
        {
            ViewData["Title"] = "Upcoming Nerd Dinners";
            DateTime d = DateTime.Now.AddMonths(2);
            var model = from dinner in db.Dinners
                        where dinner.EventDate < d
                        orderby dinner.EventDate descending
                        select dinner;
            return View("WebSlice", model.Take(5));
        }
    }
}

src/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NerdDinner.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Organizing the world's nerds and helping them eat in packs.";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }
}
}

src/Controllers/SearchController.cs
using NerdDinner.Models;
using NerdDinner.Services;
using System;
using System.Collections.Generic;
using System.Data.Spatial;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace NerdDinner.Controllers
{
    public class JsonDinner
    {
        public int DinnerID { get; set; }
        public DateTime EventDate { get; set; }
        public string Title { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Description { get; set; }
        public int RSVPCount { get; set; }
        public string Url { get; set; }
    }

    public class SearchController : ApiController
    {
        private NerdDinnerContext db = new NerdDinnerContext();

        // GET api/Search?latitude=1.0&longitude=1.0
        [HttpGet]
        public IEnumerable<JsonDinner> SearchByLocation(double latitude, double longitude)
        {
            return FindByLocation(latitude, longitude);
        }

        // GET api/Search?location=30901
        // GET api/Search?location=Seattle
        [HttpGet]
        public IEnumerable<JsonDinner> SearchByPlaceNameOrZip(string location)
        {
            if (String.IsNullOrEmpty(location)) return null;
            LatLong foundlocation = GeolocationService.PlaceOrZipToLatLong(location);
            if (foundlocation != null)
            {
                return FindByLocation(foundlocation.Lat, foundlocation.Long).
                                OrderByDescending(p => p.EventDate);
            }
            return null;
        }

        // POST api/Search?limit=10
        [HttpPost]
        public IEnumerable<JsonDinner> GetMostPopularDinners(int limit)
        {
            var mostPopularDinners = from dinner in db.Dinners.Include("RSVPs")
                                     where dinner.EventDate >= DateTime.Now
                                     orderby dinner.RSVPs.Count descending
                                     select dinner;

            return mostPopularDinners.Take(limit).AsEnumerable().Select(item => JsonDinnerFromDinner(item));
        }

        protected IQueryable<JsonDinner> FindByLocation(double latitude, double longitude)
        {
            var sourcePoint = DbGeography.FromText(string.Format("POINT ({0} {1})", longitude, latitude));

            var results =
                db.Dinners
                .Where(loc => loc.Location.Distance(sourcePoint) < 2000)
                .OrderBy(loc => loc.Location.Distance(sourcePoint));

            foreach (Dinner dinner in results)
            {
                dinner.RSVPs = new List<RSVP>();

                var rsvps = db.RSVPs.Where(x => x.DinnerID == dinner.DinnerID);

                foreach (RSVP rsvp in rsvps)
                {
                    dinner.RSVPs.Add(rsvp);
                }
            }

            var jsonDinners = results.AsEnumerable()
                    .Select(item => JsonDinnerFromDinner(item));

            return jsonDinners.AsQueryable<JsonDinner>();
        }

        private JsonDinner JsonDinnerFromDinner(Dinner dinner)
        {
            return new JsonDinner
            {
                DinnerID = dinner.DinnerID,
                EventDate = dinner.EventDate,
                Latitude = dinner.Location.Latitude.Value,
                Longitude = dinner.Location.Longitude.Value,
                Title = dinner.Title,
                Description = dinner.Description,
                RSVPCount = dinner.RSVPs.Count(),
                Url = dinner.DinnerID.ToString()
            };
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h2>What is NerdDinner.com?</h2>
</hgroup>

<article>
    <p>
        <img src="~/Images/nerd.jpg" height="200" style="float: left; padding-right: 20px" alt="Picture of a huge nerd." />Are you a huge nerd? Perhaps a geek? No? Maybe a dork, dweeb or wonk. 
	Quite possibly you're just a normal person. Either way, you're a social being. You need to get out for a bite
	to eat occasionally, preferably with folks that are like you.
    </p>
    <p>
        Enter <a href="http://www.nerddinner.com">NerdDinner.com</a>, for all your event planning needs. We're focused on one thing. Organizing the world's
	nerds and helping them eat in packs.
    </p>
    <p>We're free and fun. <a href="~/">Find a dinner near you</a>, or <a href="~/Dinners/Create">host a dinner</a>. Be social.</p>
    <p>
        We also have blog badges and widgets that you can install on your blog or website so your readers can get 
	involved in the Nerd Dinner movement. Well, it's not really a movement. Mostly just geeks in a food court, but still.
    </p>
</article>

src/Views/Home/Index.Mobile.cshtml
@{
    ViewBag.Title = "Nerd Dinner Mobile";
    Layout = "~/Views/Shared/_Layout.Mobile.cshtml";
}
<p>
    <img alt="nerddinner" src="@Url.Content("~/Content/Img/Mobile/logo_medium_trans.png")" runat="server" /></p>
<p>
    Find a Nerd Dinner near you!</p>
@using (Html.BeginForm("SearchByPlaceNameOrZip", "Search", FormMethod.Post))
{
    <div data-role="fieldcontain">
        <input type="search" name="Location" id="Location" value="" />
    </div>    
    <input id="search" type="submit" value="Search" />
}
<script type="text/javascript">
    $(document).ready(function () {
        NerdDinner.ipInfoDbKey = '@System.Configuration.ConfigurationManager.AppSettings["ipInfoDbKey"]';
        NerdDinner.BingMapsKey = '@System.Configuration.ConfigurationManager.AppSettings["BingMapsKey"]';
        yepnope({
            test: Modernizr.geolocation,
            yep: '@Url.Content("~/Scripts/geo.js")',
            nope: '@Url.Content("~/Scripts/geo-polyfill.js")',
            callback: function (url, result, key) {
                getCurrentLocation();
            }
        });

        $('#search').click(function () { if ($('#Location').val().length == 0) { alert('Please provide a location to search near'); return false;  } });
    });
</script>

src/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Nerd Dinner";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <h3>Find a Dinner</h3>
    <div id="theMap" style="position: relative; width: 580px; height: 400px;">
    </div>
</article>

<aside>
    <div>
        <div id="searchBox">
            <div class="search-text">
                Enter your location or <strong>@Html.ActionLink("View All Upcoming Dinners", "Index", "Dinners")</strong>.</div>
            @Html.TextBox("SearchLocation")
            <input id="search" type="submit" value="Search" />
        </div>        
    </div>
    <div class='hslice' id='2'>
        <h3>Popular Dinners</h3>
        <ul class="entry-content" id="dinnerList" data-bind="foreach: dinners">
            <li class="dinnerItem">
                <a data-bind="attr: { href: Url }, text: Title"></a>
                <br />
                <strong data-bind="dateString: EventDate, datePattern: 'mmm d'"></strong><span data-bind="rsvpMessage: RSVPCount"></span>
            </li>
        </ul>
        <a rel='feedurl' href='/Dinners/WebSlicePopular' style='display: none;'></a>
    </div>
</aside>

@section Scripts {
    <script type="text/javascript">
        $().ready(function () {
            yepnope({
                test: Modernizr.geolocation,
                yep: '@Url.Content("~/Scripts/geo.js")',
                nope: '@Url.Content("~/Scripts/geo-polyfill.js")',
                callback: function (url, result, key) {
                    OnNavigation();
                }
            });

            $("#search").click(ValidateAndFindDinners);

            $("#SearchLocation").keypress(function (evt) {
                if (evt.which == 13) {
                    ValidateAndFindDinners();
                }
            });
        });

        function OnNavigation() {
            NerdDinner.LoadMap(null, null);
            NerdDinner.FindMostPopularDinners(8);

            getCurrentLocation();
        }

        function ValidateAndFindDinners() {
            var where = $('#SearchLocation').val().trim();

            if (where.length < 1)
                return;

            NerdDinner.FindDinnersGivenLocation(where);
        }
    </script>
}